---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang

inputs:
- name: s3-resource
  path: gopath/src/github.com/concourse/s3-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/s3-resource/ci/build.sh
